

export const BASE_URL="http://localhost:8080/";
export const ASSET_FETCH_ALL="ASSET/FETCHALL";
export const ASSET_FETCH_BYID="ASSET/FETCHBYID";
export const ADD_ASSET="ASSET/ADDSUCCESS";
export const UPDATE_ASSET="ASSET/UPDATESUCCESS";
export const ASSET_DELETE_BYID="ASSET/DELETEBYID";
export const ASSET_FETCHALL_BYPRICE="ASSET/FETCHALL/BYPRICE";
export const ASSET_FETCHALL_BYNAME="ASSET/FETCHALL/BYNAME";
export const ASSET_FETCHALL_BYCATEGORY="ASSET/FETCHALL/BYCATEGORY";
export const  ASSET_FETCHALL_BYTYPE="ASSET/FETCHALL/BYTYPE";